ADD new deployment

diff --git a/deployment/healthcheck b/deployment/healthcheck
--- a/deployment/healthcheck
+++ b/deployment/healthcheck
@@ -5,13 +5,30 @@ set -e
 container_mode=${CONTAINER_MODE:-"http"}
 
 if [ "${container_mode}" = "http" ]; then
-    php artisan octane:status
+    php "${ROOT}/artisan" octane:status
 elif [ "${container_mode}" = "horizon" ]; then
-    php artisan horizon:status
+    php "${ROOT}/artisan" horizon:status
 elif [ "${container_mode}" = "scheduler" ]; then
-    supervisorctl status scheduler:scheduler_00
+    if [ "$(supervisorctl status scheduler:scheduler_0 | awk '{print tolower($2)}')" = "running" ]; then
+        exit 0
+    else
+        echo "Healthcheck failed."
+        exit 1
+    fi
+elif [ "${container_mode}" = "reverb" ]; then
+    if [ "$(supervisorctl status reverb:reverb_0 | awk '{print tolower($2)}')" = "running" ]; then
+        exit 0
+    else
+        echo "Healthcheck failed."
+        exit 1
+    fi
 elif [ "${container_mode}" = "worker" ]; then
-    supervisorctl status worker:worker_00
+    if [ "$(supervisorctl status worker:worker_00 | awk '{print tolower($2)}')" = "running" ]; then
+        exit 0
+    else
+        echo "Healthcheck failed."
+        exit 1
+    fi
 else
     echo "Container mode mismatched."
     exit 1
